### ISSUE TITLE
"packages", artefacts  approach

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Laravel-Package-Docker-Development-Tools#1]
Maciek what about folder "packages" approach ? Doable ?

**Comment by raczekm** [comment]
> Maciek what about folder "packages" approach ? Doable ?

Definitely worth the time to develop

**Comment by qunabu** [comment]
please check my update https://github.com/EscolaLMS/Laravel-Package-Docker-Development-Tools in the readme and files
